#IF STATEMENT
'''num=int(input("enter number"))
if num>0:
    print("number is positive")'''



'''age=int(input("enter age"))
if age>18:
    print("adult")'''



'''num=12
if num>0:
    print("number is positive")

num=-12
if num>0:
    print("number is negative")'''
#IF statement
'''age=int(input("enter number"))
if age>18:
    print("user is adult")
else:
    print("user is not adult")'''

#ODD OR EVEN

'''num=int(input("enter number"))
if num %2==0:
    print("number is even")
else:
    print("number is odd")'''

#divided byy 5
'''num=int(input("enter number"))
if num%5==0:
    print("number is divided")
else:
    print("number is not divided")'''

#number is divided by 5 or 7

'''num=int(input("enter number"))
if num%5==0 and num%7==0:
 print("number is divided by 5&7")
else:
    print("number is not divided 5&7")'''