count =0      #variable declare kare

while count < 5:  #condtion
    print(count)
    count=count+1

#print number from 1 to 5 using while loop

count =1      #variable declare kare

while count < 6:  #condtion
    print(count)
    #count=count+1
    count+=1


#negative
count =5      #variable declare kare

while count > 0:  #condtion
    print(count)
    count -= 1
else:
    print("while loop ended")