Lan = 'Python'
for i in Lan:
    print(i)

#range function
#range(stop)  ek value hoy to stop value hoy
#range(start,stop)  2 value hoy to start stop hoy
#range(start,stop,step)

for i in range(5): #5 ne include nai kare eni agad na badha element ne include karse
    print(i)

for i in range(5,10):
    print(i)

for i in range(1,10,2):
    print(i)

for i in range(5):
    print(i)
else:
    print("for loop ended")