#ELIF STATEMENT
'''num=int(input("enter number"))
if num>0:
    print("number is positive")
elif num<0:
    print("number is negative")
else:
    print("number is zero")'''


#input 2 values into user and check greater than or not 
'''num1=int(input("enter number"))
num2=int(input("enter another number"))
if num1>num2:
    print("num1 is greaterthan num2")
elif num2>num1:
    print("num2 is greaterthan num1")    #elif statement
else:
    print("both number are same")'''


'''#using ELIF statement
age=int(input("enter age"))
if age>=0 and age<=2:
    print("infant")
elif age>=3 and age<=18:
    print("minor")
elif age>=19 and age<=50:
    print("adult")
elif age>=51 and age<=70:
    print("senior")
elif age>=71:
    print("super senior")
else:
    print("age is invalid")'''

