#nestedif statement
'''age=int(input("enter age"))
weight=int(input("enter weight"))
if age>18:
    if weight>0:
        print("user is eligible to donate blood")
    else:
        print("Due to under weight user can not donate blood")
else:
    print("not eligible to donate blood ")'''

'''age=int(input("enter age"))
license=input("do user have a learning licence??")
if age>18:
    
     if license=="yes":
     #if license=="yes" or license=="YES":
     #if license in("yes","YES"):
        print("user is eligible for license")
    else:
        print("USer is not eligible for license , user doesn't have learning license")
else:
    print("user is not adult so not eligible for license")'''


'''month=input("enter month :--")
if month in ("january","march","may","july","august","october","december"):
            print("31 days")
elif month in("february"):
    print("28/29 days")
elif month in("april","june","september","november"):
 print("30 days")
else:
      print("month is invalid")'''


#leap year or not

'''year=int(input("enter year"))
if year % 4==0:
    print("leap year") 
else:
    print("not leap year")     '''

'''marks=int(input("enter marks:--"))
if marks>=70 and marks<=100:
    print("A")
elif marks>=60 and marks<=69:
    print("B")
elif marks>=40 and marks<=59:
    print("C")
elif marks>=30 and marks<=49:
    print("PASS")'''


